# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ortham’s Software Notes
name: Oliver Hamlet
email: oliver.hamlet@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Writing about my software projects and related topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ortham.github.io # the base hostname & protocol for your site, e.g. http://example.com
repository: Ortham/ortham.github.io
locale: en-GB
include: ["_pages"]
date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.13.0
plugins:
  # GitHub Pages: Enabled by default
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-remote-theme
  # GitHub Pages: Optional
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-mentions
  - jemoji

# GitHub Pages: Hardcoded settings
lsi: false
safe: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Pagination plugin
paginate: 10 # amount of posts to show

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# minimal-mistakes
minimal_mistakes_skin: dark
head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.js
footer:
  links:
    - label: Donate
      icon: fab fa-fw fa-paypal
      url: https://www.paypal.me/OliverHamlet
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/Ortham
    - label: Email
      icon: fas fa-fw fa-at
      url: mailto:oliver.hamlet@gmail.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
