baseURL = 'https://blog.ortham.net/'
languageCode = 'en-GB'
title = "Ortham's Software Notes"
theme = "congo"

paginate = 10

[[menus.main]]
name = "Posts"
pageRef = "/posts"
weight = 10

[[menus.main]]
name = "Projects"
pageRef = "/projects"
weight = 20

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 30

[markup.goldmark.renderer]
unsafe = true # Needed to render HTML blocks in Markdown

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

# Congo theme settings
[params.author]
name = "Oliver Hamlet"

colorScheme = "cherry"

[params.homepage]
showRecent = true
recentLimit = 10

[params.footer]
showAppearanceSwitcher = true
showThemeAttribution = false

[[menus.footer]]
name = "GitHub"
url = "https://github.com/Ortham"
[menus.footer.params]
icon = "github"
target = "_blank"

[[menus.footer]]
name = "Email"
url = "mailto:blog@ortham.net"
[menus.footer.params]
icon = "email"
target = "_blank"

[[menus.footer]]
name = "PayPal"
url = "https://www.paypal.me/OliverHamlet"
[menus.footer.params]
icon = "paypal"
target = "_blank"

[[menus.main]]
identifier = "appearance"
weight = 99
[menus.main.params]
action = "appearance"

[params.article]
showDate = false
showDateUpdated = false
showAuthor = false
showReadingTime = false

[params.list]
groupByYear = false
